import * as prismStyles from "react-syntax-highlighter/dist/esm/styles/prism";
import * as hljs from "react-syntax-highlighter/dist/esm/styles/hljs";
import style from "react-syntax-highlighter/dist/esm/styles/hljs/a11y-dark";
const themes = [
  { name: "a11y Dark", style: hljs.a11yDark },
  { name: "a11y Light", style: hljs.a11yLight },
  { name: "agate", style: hljs.agate },
  { name: "an Old Hope", style: hljs.anOldHope },
  { name: "androidstudio", style: hljs.androidstudio },
  { name: "arduino Light", style: hljs.arduinoLight },
  { name: "arta", style: hljs.arta },
  { name: "ascetic", style: hljs.ascetic },
  { name: "atelier Cave Dark", style: hljs.atelierCaveDark },
  { name: "atelier Cave Light", style: hljs.atelierCaveLight },
  { name: "atelier Dune Dark", style: hljs.atelierDuneDark },
  { name: "atelier Dune Light", style: hljs.atelierDuneLight },
  { name: "atelier Estuary Dark", style: hljs.atelierEstuaryDark },
  { name: "atelier Estuary Light", style: hljs.atelierEstuaryLight },
  { name: "atelier Forest Dark", style: hljs.atelierForestDark },
  { name: "atelier Forest Light", style: hljs.atelierForestLight },
  { name: "atelier Heath Dark", style: hljs.atelierHeathDark },
  { name: "atelier Heath Light", style: hljs.atelierHeathLight },
  { name: "atelier Lakeside Dark", style: hljs.atelierLakesideDark },
  { name: "atelier Lakeside Light", style: hljs.atelierLakesideLight },
  { name: "atelier Plateau Dark", style: hljs.atelierPlateauDark },
  { name: "atelier Plateau Light", style: hljs.atelierPlateauLight },
  { name: "atelier Savanna Dark", style: hljs.atelierSavannaDark },
  { name: "atelier Savanna Light", style: hljs.atelierSavannaLight },
  { name: "atelier Seaside Dark", style: hljs.atelierSeasideDark },
  { name: "atelier Seaside Light", style: hljs.atelierSeasideLight },
  { name: "atelier Sulphurpool Dark", style: hljs.atelierSulphurpoolDark },
  { name: "atelier Sulphurpool Light", style: hljs.atelierSulphurpoolLight },
  { name: "atom One Dark Reasonable", style: hljs.atomOneDarkReasonable },
  { name: "atom One Dark", style: hljs.atomOneDark },
  { name: "atom One Light", style: hljs.atomOneLight },
  { name: "brown Paper", style: hljs.brownPaper },
  { name: "codepen Embed", style: hljs.codepenEmbed },
  { name: "color Brewer", style: hljs.colorBrewer },
  { name: "darcula", style: hljs.darcula },
  { name: "dark", style: hljs.dark },
  { name: "default Style", style: hljs.defaultStyle },
  { name: "docco", style: hljs.docco },
  { name: "dracula", style: hljs.dracula },
  { name: "far", style: hljs.far },
  { name: "foundation", style: hljs.foundation },
  { name: "github Gist", style: hljs.githubGist },
  { name: "github", style: hljs.github },
  { name: "gml", style: hljs.gml },
  { name: "googlecode", style: hljs.googlecode },
  { name: "gradient Dark", style: hljs.gradientDark },
  { name: "grayscale", style: hljs.grayscale },
  { name: "gruvbox Dark", style: hljs.gruvboxDark },
  { name: "gruvbox Light", style: hljs.gruvboxLight },
  { name: "hopscotch", style: hljs.hopscotch },
  { name: "hybrid", style: hljs.hybrid },
  { name: "idea", style: hljs.idea },
  { name: "ir Black", style: hljs.irBlack },
  { name: "isbl Editor Dark", style: hljs.isblEditorDark },
  { name: "isbl Editor Light", style: hljs.isblEditorLight },
  { name: "kimbie.dark", style: hljs.kimbieDark },
  { name: "kimbie.light", style: hljs.kimbieLight },
  { name: "lightfair", style: hljs.lightfair },
  { name: "lioshi", style: hljs.lioshi },
  { name: "magula", style: hljs.magula },
  { name: "mono Blue", style: hljs.monoBlue },
  { name: "monokai Sublime", style: hljs.monokaiSublime },
  { name: "monokai", style: hljs.monokai },
  { name: "night Owl", style: hljs.nightOwl },
  { name: "nnfx Dark", style: hljs.nnfxDark },
  { name: "nnfx", style: hljs.nnfx },
  { name: "nord", style: hljs.nord },
  { name: "obsidian", style: hljs.obsidian },
  { name: "ocean", style: hljs.ocean },
  { name: "paraiso Dark", style: hljs.paraisoDark },
  { name: "paraiso Light", style: hljs.paraisoLight },
  { name: "pojoaque", style: hljs.pojoaque },
  { name: "purebasic", style: hljs.purebasic },
  { name: "qtcreator Dark", style: hljs.qtcreatorDark },
  { name: "qtcreator Light", style: hljs.qtcreatorLight },
  { name: "railscasts", style: hljs.railscasts },
  { name: "rainbow", style: hljs.rainbow },
  { name: "routeros", style: hljs.routeros },
  { name: "school Book", style: hljs.schoolBook },
  { name: "shades Of Purple", style: hljs.shadesOfPurple },
  { name: "solarized Dark", style: hljs.solarizedDark },
  { name: "solarized Light", style: hljs.solarizedLight },
  { name: "srcery", style: hljs.srcery },
  { name: "stackoverflow Dark", style: hljs.stackoverflowDark },
  { name: "stackoverflow Light", style: hljs.stackoverflowLight },
  { name: "sunburst", style: hljs.sunburst },
  { name: "tomorrow Night Blue", style: hljs.tomorrowNightBlue },
  { name: "tomorrow Night Bright", style: hljs.tomorrowNightBright },
  { name: "tomorrow Night Eighties", style: hljs.tomorrowNightEighties },
  { name: "tomorrow Night", style: hljs.tomorrowNight },
  { name: "tomorrow", style: hljs.tomorrow },
  { name: "vs", style: hljs.vs },
  { name: "vs2015", style: hljs.vs2015 },
  { name: "xcode", style: hljs.xcode },
  { name: "xt256", style: hljs.xt256 },
  { name: "zenburn", style: hljs.zenburn }
];
const languages = [
  "javascript",
  "cpp",
  "c",
  "python",
  "java",
  "ruby",
  "go",
  "swift",
  "typescript",
  "rust",
  "php",
  "html",
  "css",
  "sass",
  "scss",
  "bash",
  "powershell",
  "perl",
  "lua",
  "kotlin",
  "r",
  "scala",
  "groovy",
  "dart",
  "haskell",
  "elixir",
  "erlang",

  "coffeescript",
  "f#",
];

export { themes, languages };
